version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/thinksurance
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/thinksurance
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./var/log/thinksurance:/var/log/thinksurance
    links:
      - mysql
  mysql:
    image: mysql:5.7.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thinksurance
      MYSQL_USER: thinksurance-user
      MYSQL_PASSWORD: thinksurance-pass
    ports:
      - "3307:3306"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /var/www/thinksurance
    environment:
      - NGINX_HOST=thinksurance.local
    volumes:
      - ./:/var/www/thinksurance
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./var/log/nginx/:/var/log/nginx/
    links:
      - php