<?php

namespace App\Tests\Services\PigLatin;

use App\Services\PigLatin\PigLatinService;
use PHPUnit\Framework\TestCase;

class PigLatinServiceTest extends TestCase
{
    /**
     * @var \App\Services\PigLatin\PigLatinService
     */
    private PigLatinService $PigLatinService;

    protected function setUp() : void {
        parent::setUp();
        $this->PigLatinService = new PigLatinService();
    }


    /**
     * @dataProvider providePigLatin
     *
     * @param $original
     * @param $pigLatin
     */
    public function testConvert($original, $pigLatin) {
        $converted = $this->PigLatinService->convert($original);
        $this->assertEquals($pigLatin, $converted, "Unexpected PigLatin conversion from '$original' to '$converted' when it should be '$pigLatin'");
    }

    /**
     * @dataProvider providePigLatin
     *
     * @param $notPigLatin
     * @param $pigLatin
     */
    public function testIsPigLatin($notPigLatin, $pigLatin) {
        $isPigLatin = $this->PigLatinService->isPigLatin($pigLatin);
        $this->assertEquals(true, $isPigLatin, "Unexpected PigLatin invalidation for '$pigLatin' when it should be valid");

        $isPigLatin = $this->PigLatinService->isPigLatin($notPigLatin);
        $this->assertEquals(false, $isPigLatin, "Unexpected PigLatin validation for '$notPigLatin' when it should be invalid");
    }

    public function providePigLatin() : array {
        return [
            //<weird english words section according to https://www.ef.com/wwen/blog/language/12-weirdest-words-in-english/>
            [
                'gerrymandering',
                'errymanderinggay',
            ],
            [
                'fungus',
                'ungusfay',
            ],
            [
                'aa',
                'aayay',
            ],
            [
                'queue',
                'ueueqay',
            ],
            [
                'vex',
                'exvay',
            ],
            [
                'bequeath',
                'equeathbay',
            ],
            [
                'mixology',
                'ixologymay',
            ],
            [
                'flub',
                'ubflay',
            ],
            [
                'kerfuffle',
                'erfufflekay',
            ],
            [
                'bibble',
                'ibblebay',
            ],
            [
                'kakorrhaphiophobia',
                'akorrhaphiophobiakay',
            ],
            [
                'berserk',
                'erserkbay',
            ],
            //</weird english words section according to https://www.ef.com/wwen/blog/language/12-weirdest-words-in-english/>
            [
                'by',
                'ybay',
            ],
            [
                'yea',
                'eayay',
            ],
            [
                'eye',
                'eyeyay',
            ],
            [
                'center',
                'entercay',
            ],
            [
                'center',
                'entercay',
            ],
            [
                'tomorrow',
                'omorrowtay',
            ],
            [
                'pig',
                'igpay',
            ],
            [
                'latin',
                'atinlay',
            ],
            [
                'banana',
                'ananabay',
            ],
            [
                'will',
                'illway',
            ],
            [
                'butler',
                'utlerbay',
            ],
            [
                'happy',
                'appyhay',
            ],
            [
                'duck',
                'uckday',
            ],
            [
                'me',
                'emay',
            ],
            [
                'bagel',
                'agelbay',
            ],
            [
                'smile',
                'ilesmay',
            ],
            [
                'string',
                'ingstray',
            ],
            [
                'stupid',
                'upidstay',
            ],
            [
                'glove',
                'oveglay',
            ],
            [
                'trash',
                'ashtray',
            ],
            [
                'floor',
                'oorflay',
            ],
            [
                'store',
                'orestay',
            ],
            [
                'eat',
                'eatyay',
            ],
            [
                'omelet',
                'omeletyay',
            ],
            [
                'are',
                'areyay',
            ],
            [
                'egg',
                'eggyay',
            ],
            [
                'explain',
                'explainyay',
            ],
            [
                'always',
                'alwaysyay',
            ],
            [
                'ends',
                'endsyay',
            ],
            [
                'honest',
                'onesthay',
            ],
            [
                'I',
                'Iyay',
            ],
            [
                'yellow',
                'ellowyay',
            ],
            [
                'yacht',
                'achtyay',
            ],
            [
                'these',
                'esethay',
            ],
            [
                'violent',
                'iolentvay',
            ],
            [
                'delights',
                'elightsday',
            ],
            [
                'have',
                'avehay',
            ],
            [
                'violent',
                'iolentvay',
            ],
            [
                'ends',
                'endsyay',
            ],
            [
                'and',
                'andyay',
            ],
            [
                'in',
                'inyay',
            ],
            [
                'their',
                'eirthay',
            ],
            [
                'triumph',
                'iumphtray',
            ],
            [
                'die',
                'ieday',
            ],
            [
                'like',
                'ikelay',
            ],
            [
                'fire',
                'irefay',
            ],
            [
                'powder',
                'owderpay',
            ],
            [
                'which',
                'ichwhay',
            ],
            [
                'as',
                'asyay',
            ],
            [
                'they',
                'eythay',
            ],
            [
                'kiss',
                'isskay',
            ],
            [
                'consume',
                'onsumecay',
            ],
            [
                'my',
                'ymay',
            ],
            [
                'bounty',
                'ountybay',
            ],
            [
                'is',
                'isyay',
            ],
            [
                'boundless',
                'oundlessbay',
            ],
            [
                'the',
                'ethay',
            ],
            [
                'sea',
                'easay',
            ],
            [
                'love',
                'ovelay',
            ],
            [
                'deep',
                'eepday',
            ],
            [
                'more',
                'oremay',
            ],
            [
                'give',
                'ivegay',
            ],
            [
                'to',
                'otay',
            ],
            [
                'thee',
                'eethay',
            ],
            [
                'have',
                'avehay',
            ],
            [
                'for',
                'orfay',
            ],
            [
                'both',
                'othbay',
            ],
            [
                'are',
                'areyay',
            ],
            [
                'infinite',
                'infiniteyay',
            ],
        ];
    }
}
